### ISSUE TITLE
国交省データの出典について

### ISSUE THREAD

**Issue by ozt-ca** [rindybell/kokkosho_data#1]
もし可能であれば、こちらで公開されている国交省データの出典について教えていただけませんでしょうか？

**Comment by rindybell** [comment]
返答遅くなり失礼いたしました。
README.mdに記載しましたので、ご確認いただければと思います。

**Comment by ozt-ca** [comment]
こちら、ご対応下さいましてまことに有難うございました。取り急ぎ。
